"""projects, graphs, risks, runs

Revision ID: 711cc0e45c33
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '711cc0e45c33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('system_name', sa.Text(), nullable=False),
    sa.Column('qualification_id', sa.Text(), nullable=False),
    sa.Column('objectives_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_qualification_id'), 'project', ['qualification_id'], unique=False)
    op.create_table('answer',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('high_risk', sa.Boolean(), nullable=False),
    sa.Column('personal_data', sa.Boolean(), nullable=False),
    sa.Column('interacts_with_natural_persons', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('graph',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('jsonld', sa.Text(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('risks', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('mapping_run',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stop', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('profile_run',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stop', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('risk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('risk_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('short_label', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('vulnerability', sa.Text(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=False),
    sa.Column('stakeholder', sa.Text(), nullable=False),
    sa.Column('control', sa.Text(), nullable=False),
    sa.Column('follow_up_control', sa.Text(), nullable=False),
    sa.Column('areas', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('vair_terms', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'risk_id')
    )
    op.create_index(op.f('ix_risk_project_id'), 'risk', ['project_id'], unique=False)
    op.create_table('mapped_objective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_row_id', sa.Integer(), nullable=False),
    sa.Column('objective_id', sa.Text(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['risk_row_id'], ['risk.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_row_id', 'objective_id')
    )
    op.create_index(op.f('ix_mapped_objective_risk_row_id'), 'mapped_objective', ['risk_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapped_objective_risk_row_id'), table_name='mapped_objective')
    op.drop_table('mapped_objective')
    op.drop_index(op.f('ix_risk_project_id'), table_name='risk')
    op.drop_table('risk')
    op.drop_table('profile_run')
    op.drop_table('mapping_run')
    op.drop_table('graph')
    op.drop_table('answer')
    op.drop_index(op.f('ix_project_qualification_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
