"""drop the profile run and the answer

Revision ID: 085f844985f5
Revises: 711cc0e45c33
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '085f844985f5'
down_revision = '711cc0e45c33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('profile_run')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_run',
    sa.Column('project_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('stop', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ran_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('profile_run_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('profile_run_pkey'))
    )
    op.create_table('answer',
    sa.Column('project_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('high_risk', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('personal_data', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('interacts_with_natural_persons', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('answer_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('answer_pkey'))
    )
    # ### end Alembic commands ###
